Add last updated to CMS Dashboard
CMSgov/managed-care-review pull request #1111
Opened 2022-08-09 22:42 UTC by haworku

## Summary
Add last updated and in general move from looking at current revision to previous submitted revision for form data. That's something I overlooked in the first pass at the dashboard, likely could cause bugs. 

Last updated at value should be CMS unlock time (if its unlocked) or else state submit time (if its just submitted), fall back to last updated at  for the current revision (likely we wouldn't need that but just to have something there).

#### Related issues
https://qmacbis.atlassian.net/browse/MR-2466

#### Test cases covered
COMING SOON - still updating Cypress

## QA guidance
COMING SOON

2022-08-09 22:44 UTC, haworku commented on services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx
> +                lastUpdated =
TODO: add a comment here.Last updated at value should be CMS unlock time (if its unlocked) or else state submit time (if its just submitted), fall back to last updated at  for the current revision (likely we wouldn't need that but just to have something there).

2022-08-10 21:15 UTC, JasonLin0991 requested changes
Seems to not move the recently resubmitted submission up to the top of the list.

https://user-images.githubusercontent.com/98117700/184021478-366f1661-d45c-466c-bd7c-36c9f749f7fa.mov

2022-08-10 21:48 UTC, haworku commented
Thanks @JasonLin0991 must have broken something. Will look at this and also if there's a way to catch it through tests

2022-08-11 14:59 UTC, haworku commented on services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx
> +            let lastUpdated =
Consider making a utility function to compare a set of dates and pull most recent as last updated

2022-08-11 21:06 UTC, JasonLin0991 approved these changes
Works great and thanks for those additional changes!

2022-08-12 17:01 UTC, merged