fix: previous submission link visibility, copy changes on landing, submission type pages
CMSgov/managed-care-review pull request #1160
Opened 2022-08-30 13:23 UTC by haworku

## Summary
Previous submission link:
- This effects the ChangeHistory table
- Do not show link when only one version exists. When a new version has been resubmitted, show link

Copy changes:
- On the submission type page: Change “Programs” to “Programs this contract action covers” 
- On the Homepage: Remove “CHIP-Only Submissions” and “Documents for pre-review” from  the “Not accepted at this time” list. 

Cypress:
- Added new helpers `navigateFormByDirectLink` (formerly inline cy.visit scattered around),  `navigateFormByButtonClick` (formerly navigateForm) 
-
#### Related issues
https://qmacbis.atlassian.net/browse/MR-2465
https://qmacbis.atlassian.net/browse/MR-2422

#### Test cases covered
- 'should not include link to previous submission for the initial submission in the list'

## QA guidance
- Please do manual QA of the change history table in general. Including validating the submission versions linked are correct.

2022-08-31 17:14 UTC, JasonLin0991 requested changes
The copy changes look good. There seems to be a few issues on the change history work.

In the screen shot below. As a State or CMS user the most recent submission, when submission is not unlocked, should not have a link.
<img src="https://user-images.githubusercontent.com/98117700/187736674-29e51adb-b253-461e-ba57-aa1242e53be0.png" width="400"/>.

If we had multiple submissions and unlocks, the initial submission should have a link.
<img src="https://user-images.githubusercontent.com/98117700/187738678-11557a5b-fb47-450d-95a0-27e661eb4761.png" width="400"/>.

2022-08-31 19:36 UTC, JasonLin0991 commented
Forgot to mention in the review that the date time listed for submissions, does not match up with the date time when viewing previous submission.

2022-09-01 20:38 UTC, haworku commented on services/app-web/src/components/ChangeHistory/ChangeHistory.tsx
> +        // We want to know if this package has multiple submissions. To have multiple submissions, there must be minimum
Thank you! this comment is clarifying lol :)

2022-09-01 20:40 UTC, haworku reviewed
🥇 Really like this change. Thanks for finding a clear way to call out how this link should display in the code. you will have to approve to merge

2022-09-01 20:49 UTC, rswerve commented
Works as described and code looks good.

2022-09-01 20:49 UTC, rswerve approved these changes

2022-09-01 21:12 UTC, JasonLin0991 approved these changes
I also approve my changes.😎

2022-09-01 21:12 UTC, merged