MR-2844 Rates Across Subs should use radio buttons
CMSgov/managed-care-review pull request #1364
Opened 2022-12-05 23:32 UTC by haworku

## Summary
Use radio buttons instead of checkbox on rates across subs. Also add design tweaks for summary page work.

#### Related issues
https://qmacbis.atlassian.net/browse/MR-2844
See design tweak comments on https://qmacbis.atlassian.net/browse/MR-2686

#### Screenshots
![Screen Shot 2022-12-05 at 5 15 13 PM](https://user-images.githubusercontent.com/10750442/205766158-1d09ff00-c51b-4589-85c1-400076911036.png)
![Screen Shot 2022-12-05 at 5 12 25 PM](https://user-images.githubusercontent.com/10750442/205766216-0712245a-872e-49ad-a31c-53d6bf97fa9e.png)

#### Test cases covered
- No new tests, had to fix tests to work for the radio buttons
- Our tests are really long in RateDetails, we need to simplify. Felt like this was out scope for this ticket but this is also the test we have periodic timeouts in unit tests because we are doing a lot. 

## QA guidance
- There should be no change in the data stored or behaviors on edit. The radio button is UI only and not stored as a field in db, we just store the programs list in the associated dropdown that appears when you click "Yes".
- Validations state work checking, for yes, no, yes with the dropdown selecton, yes with dropdown.

2022-12-06 21:04 UTC, JasonLin0991 requested changes
1️⃣ Bug. 1️⃣ Styling. Other wise looks good.

2022-12-06 21:28 UTC, JasonLin0991 requested changes
See above. I'm pretty sure I selected `Requested changes` and not `Comments`.

2022-12-06 22:41 UTC, haworku commented on services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
> +                                                                        label="Yes"
Thanks, addressed in [de08cfc](https://github.com/CMSgov/managed-care-review/pull/1364/commits/de08cfc993000b2ceffe4f918b788d28a9699b51)

2022-12-07 01:03 UTC, JasonLin0991 approved these changes
Thanks for the bug fix!

2022-12-07 14:29 UTC, merged