MR-308 Move contract type buttons to submission type page
CMSgov/managed-care-review pull request #1394
Opened 2022-12-21 16:11 UTC by rswerve

## Summary

To support future branching workflows, we need users to select a contract type earlier in the process.  This PR moves them to the first page of user responses.

In addition, there was a big refactor of the proto snapshot tests, which simply don't work properly when they include async calls.  I rewrote them as regular assertions (which also didn't work in a loop, so there's a lot of duplication now).  Even these will probably need to be refactored, when we fully understand what's going on with our saved protos, which brings us to...

...the saved protos are odd, because some of them were no different than their predecessor (I've deleted those), which shouldn't really happen.

#### Screenshots

<img width="657" alt="image" src="https://user-images.githubusercontent.com/8964335/208950729-27e612ab-558e-4062-99f6-f96d779521b3.png">

#### Test cases covered

Wrote new tests for the submission type page, and refactored cypress shared commands to handle the new flow.

2022-12-21 19:48 UTC, JasonLin0991 requested changes
`Contract action type` should be move to the `SubmissionTypeSummary` section. 
<img src="https://user-images.githubusercontent.com/98117700/208990463-54d090d4-2337-40d0-8224-c63fe97e38a6.png" width="500"/>

Just a reminder, on the summary pages, the `Submitted` details is on its own row which is intended. Incase you saw it and wondered if this was intentional.
<img src="https://user-images.githubusercontent.com/98117700/208990634-744f4632-0db0-4fcb-9c87-a25b0b5f25ba.png" width="500"/>

2022-12-21 19:56 UTC, macrael commented on services/app-web/package.json
> +        "test:once": "TZ=UTC react-scripts test --watchAll=false --runInBand --ci",
oof that must be a fun one

2022-12-21 20:08 UTC, macrael approved these changes
nice work

2022-12-21 20:08 UTC, macrael commented on services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetailsSchema.ts
> +        ),
There might be a way to put all of these in a conditional inside this yup object instead of making the yesNoError take a parameter

2022-12-21 22:14 UTC, rswerve commented
> `Contract action type` should be move to the `SubmissionTypeSummary` section. <img alt="" width="500" src="https://user-images.githubusercontent.com/98117700/208990463-54d090d4-2337-40d0-8224-c63fe97e38a6.png">
> 
> Just a reminder, on the summary pages, the `Submitted` details is on its own row which is intended. Incase you saw it and wondered if this was intentional. <img alt="" width="500" src="https://user-images.githubusercontent.com/98117700/208990634-744f4632-0db0-4fcb-9c87-a25b0b5f25ba.png">

Good call.  Moved it over 🙂

2022-12-22 01:26 UTC, rswerve commented
> `Contract action type` should be move to the `SubmissionTypeSummary` section. <img alt="" width="500" src="https://user-images.githubusercontent.com/98117700/208990463-54d090d4-2337-40d0-8224-c63fe97e38a6.png">

oops, forgot to close the comment in the other reply

2022-12-22 20:58 UTC, merged